no-perm: "&cNo rights!"
reload: "&aConfigs succesfully reloaded!"
usages:
  - "&f/iai reload <name> - reload configs"
recipe-book:
  enabled: true
  item: "KNOWLEDGE_BOOK"
  name: "&6Recipe book"
  gui-title: "&8Recipe book"
  hidden-stations:
    - "secret_workbench"
    - "admin_furnace"