no-perm: "&cНет прав!"
reload: "&aКонфиги успешно перезагружены"
usages:
  - "&f/iai reload <name> - перезагрузить конфиги"
furnace-not-found: "&cПечка с таким названием не найдена!"
workbench-not-found: "&cВерстак с таким названием не найден!"